import React from 'react'
import PersonalStats from './PersonalStats'

export default function AboutMe() {
  return (
    <div className='AboutMe'>
      <div className='HeroAboutMe'>
        <h2 className='PageTitle'>Most of everything About Me!</h2>
        <p>short description</p>
        {/* add otter svgs */}
        {/* add logic to scroll past the short story div */}
        <button className='SkipStory'>Skip to Stats</button>
      </div>
      <PersonalStats/>
      <div className='ShortStory'>
        <h3 className='SectionTitle'>Who Am I</h3>
        <p>There are many things that make me the person that I am. I think who I am, both professionally and personally, is one and the same, while one inspires the other, the other motivates the one. I sometimes think I could write a whole novel about my life so far, but don’t worry about this being too long, this will be both as short and as sweet as me. While my life has been lived so far for a relatively short amount of time, it has also been extremely eventful and full of challenges that made me grow. The last part of that sentence, growth, is the first part of the ‘who’ I am that I would like to show.
        <br/>
        Growing on its own has always been a challenge for me, it has always been my version of Sisyphus pushing a boulder up a hill. For a long time, my hubris was thinking growth would happen on its own, I was naïve enough to believe that it would be easy and come to me naturally like it did for those around me. But I never felt like I was the same as those around me. Whether it was because of my queerness, gender expression, or my autism and ADHD (which both went undiagnosed for far too long); I was and most probably always will be fundamentally different from those around me. But me learning about myself, about the way my mind works, about my passions, and about the way I can be me in a room full of people, that is me pushing that boulder up that hill. Perhaps one day I will have grown enough to finally get that boulder to the top of that hill, and it will stay there. How do I get that boulder to stay up the hill is a question I’ve asked myself many times, which leads me to the second part that I would like to show, learning.
        <br/>
        When I was young, my mom passed down a phrase to me from her mother, ‘you will spend everyday learning something new, and one day when you get to the end of life you will realize you have barely learnt anything.’  As a kid I of course didn’t fully comprehend what it all meant. But now as I’ve gotten to live life, I hold those words to mean everything to me. My whole life I have spent my time learning three main things: what do I want out of life, the skills/knowledge I need to get what I want out of life, and how do people fit into my life. It took me a long time to figure out what I want out of life, it took me only 26 years to figure it all out. I spent my high school years and especially my university years trying to find that path that felt like it was made for me. I spent time thinking I would do something logical like get into the sciences only for the creative side of me to pull me in the opposite direction and think something in the arts was the path I should take. I went from thinking I would be an accountant to being a character designer, to a forensic scientist, to a level designer for games, to a psychologist, to a writer, to an AI quality assurance specialist, and eventually to graphic designer. All of that time was me playing tug of war in my own mind and never stopping for a moment to think that maybe I can have it all, the logical and the creative. And then I eventually realized that in 2023, I could have both, things finally settled, and I found the path I wanted. Front-end engineering is all the logic of code, while having the creativity to push that code to create something beautiful. Web development was finally a goal to achieve but the question of skill and knowledge was the next level boss I would have to face.
        <br/>
        After deciding on Front-end engineering, I pursued knowledge through Codecademy. It was a great opportunity for me to set goals for myself and to study something new in my spare time. Studying while having a full-time job was often not the easiest task, but I learnt how to be flexible with myself and to stick to the dream that I wanted. I got tired along that path, but I never gave up. Over time I started to realize I had a lot of guilt around all the paths I had abandoned before, and it felt like a room full of ghosts that haunted me, they taunted me into thinking Web Development would be another path abandoned. But I realized that those paths didn’t have to be abandoned, that they weren’t ghosts but rather bits of knowledge that I could bring back to life. That has been the last portion of my learning experience, bringing forward old knowledge, combining it with all the new knowledge I was gaining and creating something new for myself as I continue to grow both as a person and grow my Web Development skills. But there was one last skill that I needed to work on, and that skill is both the most recent way I have been using my time to grow, and it is also the last part of who I am that I want to show.
        <br/>
        People always have been the most confusing thing to me. It is a normal struggle for introverted and autistic people like me to just struggle with other people. Whether it is small talk with people, asking for help, giving an opinion or trying to form something deeper, it has always been a struggle. But there is something that motivates me about people too, and that is community. There are a few highlights in life that I can look at and say, ‘that was us, in that moment, being the best humans can be.’ The earliest moment I can recall of that was when I was in my final year of high school, and I remember in Mathematics classes we would spend half the class practicing the new concept we learned that day. I tended to finish all the practice questions quickly which led to something that I loved about those days. I would sit there with other students around me and help them figure out how to answer the practice questions by explaining the same concept but in a way that they could understand through a new perspective. A similar time of life was when I was in university, and me and my 2 best friends would sit together. Each of us would be working on our own projects but we would help each other figure out problems as they came up. Those problems might have been a bit of code that wouldn’t work the way it was expected to work, some art we couldn’t quite get to fit the right perspective or trying to figure out the best way to structure our projects. We were always there to help each other out (and spoiler alert, we still help each other out to this day, as we still try being the best friends we can be for each other).
        <br/>
        That way of being around other people even continues and informs my actions to this day as I have worked as a team lead since 2022. I have learnt to look for patterns within the work I do so that I can communicate it to the engineer that manages our AI so that we can work together to improve accuracy. I’ve learnt how to communicate with my manager so that I can fully understand projects that we work on, to make sure that the turn around of the projects are both accurate and rapid, and asking questions or raising concerns so that problems can be dealt with before they turn into disasters. And lastly, as a lead I have grown my skills of being able to look at the work that other people have done, both correcting mistakes, but also developing an understanding of why those mistakes happened so that I can formulate new ways of guiding them through projects, allowing them the time to ask questions and gaining an understanding from their perspective so that we can all grow together.
        <br/>
        This is why I love that saying from my grandmother as much as I do. To live life means to be like Sisyphus, endlessly pushing through a challenge day after day. Spending everyday learning what we can, and in learning we keep growing. And even though we will get to the end of the road not knowing everything, at least we can pass on our knowledge to those around us and help them grow. That is who I am, and who I want to be. I want to be the tree that reaches toward the sky, and in the process, I want to spread my seeds of knowledge, so that one day others can reach for that sky too.
        </p>
      </div>
    </div>
  )
}
